# Generated by Django 3.2.3 on 2021-08-03 18:48

import contratos.models.contratos
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('archivado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PF', 'Por Firmar'), ('FT', 'Firmado por Trabajador'), ('FE', 'Firmado por Empleador'), ('FF', 'Firmado'), ('OB', 'Objetado')], default='PF', max_length=2)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentosContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('archivo', models.FileField(upload_to=contratos.models.contratos.contrato_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['contrato'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('activo', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='plantillas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])])),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on  which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on  which the object was last modified.', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
