# Generated by Django 3.2.3 on 2021-08-03 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tipo_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipo',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_tipo_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_plantilla_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_plantilla_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='plantas',
            field=models.ManyToManyField(to='utils.Planta'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratos.tipo'),
        ),
        migrations.AddField(
            model_name='documentoscontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='documentoscontrato',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_documentoscontrato_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoscontrato',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_documentoscontrato_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contrato_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_contrato_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
